[[plugins]]
repo      = 'prabirshrestha/vim-lsp'
hook_add  = '''
let g:lsp_signs_enabled           = 1
let g:lsp_diagnostics_enabled     = 1
let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_virtual_text_enabled    = 1
let g:lsp_signs_error             = {'text': '✗'}
let g:lsp_signs_warning           = {'text': '‼'}
let g:lsp_signs_information       = {'text': 'i'}
let g:lsp_signs_hint              = {'text': '?'}

nm <buffer> <F12>   <plug>(lsp-definition)
nm <buffer> <F11>   <plug>(lsp-peek-definition)
nm <buffer> K       <plug>(lsp-hover)
nm <buffer> <S-F12> <plug>(lsp-references)
nm <buffer> <S-F6>  <plug>(lsp-rename)
nm <buffer> =-      <plug>(lsp-document-format)
nm <buffer> <F2>    <plug>(lsp-type-definition)
'''

[[plugins]]
repo      = 'prabirshrestha/async.vim'

[[plugins]]
repo      = 'mattn/vim-lsp-settings'
